### ISSUE TITLE
Error in import

### ISSUE THREAD

**Issue by jeremycherfas** [joshstrange/day-one-narrato-import#1]
Hi.

I tried to use your very useful script, but I am getting this error:

Jeremys-iMac:day-one-narrato-import cherfas$ node index.js import ./items.json -d '/Users/cherfas/Dropbox/Apps/Day One/Journal.dayone/'

/Users/cherfas/day-one-narrato-import/index.js:38
                item.annotations.forEach(function(annotation){
                                 ^
TypeError: Cannot call method 'forEach' of undefined
    at /Users/cherfas/day-one-narrato-import/index.js:38:22
    at Array.forEach (native)
    at Command.<anonymous> (/Users/cherfas/day-one-narrato-import/index.js:37:10)
    at Command.listener (/Users/cherfas/day-one-narrato-import/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/Users/cherfas/day-one-narrato-import/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/cherfas/day-one-narrato-import/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/cherfas/day-one-narrato-import/index.js:53:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

I moved my items.json into the day-one-narrato-import folder for ease of import.

Any ideas? I'm way out of my depth here, just following instructions.

Thanks

**Comment by joshstrange** [comment]
Jeremy, it looks like the "annotations" key on each (or at least one) of your entries is missing. I wrote this script as a one-off for myself and have not kept up with the format of narrato since creating it. That said I'm more than happy to assist.

What I need is a sample of the file you are trying to import but DO NOT post your items.json as (I'm sure you understand) this contains all of your posts and I'm guess the last thing you want to do is make that public :). Let me re-download narrato, put in some dummy data, and then take a look at the items.json file. If I can't find anything that helps me I might have you cut out part of your items.json and email it directly to me (I'll walk you through cleaning out any of your real data so that none of that comes to me, just the structure of the data). Give me a little bit of time to look into this, I'll respond back soon.

**Comment by jeremycherfas** [comment]
Dear Josh

Thanks so much for your response.

Frankly, I'm more than happy to send the whole file to you if it helps.
I'm also happy to abandon those entries; I mean, they're not THAT
important.

I'll be travelling for the next couple of days anyway, so not likely to
do much before Monday.

Thanks again

Jeremy

On Wed, 23 Sep 2015, at 02:34 PM, Josh Strange wrote:

> Jeremy, it looks like the "annotations" key on each (or at least one)
> of your entries is missing. I wrote this script as a one-off for
> myself and have not kept up with the format of narrato since creating
> it. That said I'm more than happy to assist.
> 
> What I need is a sample of the file you are trying to import but DO
> NOT post your items.json as (I'm sure you understand) this contains
> all of your posts and I'm guess the last thing you want to do is make
> that public :). Let me re-download narrato, put in some dummy data,
> and then take a look at the items.json file. If I can't find anything
> that helps me I might have you cut out part of your items.json and
> email it directly to me (I'll walk you through cleaning out any of
> your real data so that none of that comes to me, just the structure of
> the data). Give me a little bit of time to look into this, I'll
> respond back soon.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/joshstrange/day-one-narrato-import/issues/1#issuecomment-142602316

**Comment by joshstrange** [comment]
Ok, it was like I guessed, they changed the format of items.json. I got the new format and adjusted the the code to fit the new format. You will need to either update the code (if you checked out through git with a "git pull") or re-download if you just downloaded the zip file and now your items.json should work.

I didn't do a full test b/c I didn't want to re-import my entries but the code didn't change much so you should be good to go. Let me know if you run into any issues! Let me know if it worked as well and then I will close this issue.

**Comment by jeremycherfas** [comment]
Wow. Thanks. I will let you know whether this worked in a couple of
days. Running out the door.

On Wed, 23 Sep 2015, at 02:58 PM, Josh Strange wrote:

> Ok, it was like I guessed, they changed the format of items.json. I
> got the new format and adjusted the the code to fit the new format.
> You will need to either update the code (if you checked out through
> git with a "git pull") or re-download if you just downloaded the zip
> file and now your items.json should work.
> 
> I didn't do a full test b/c I didn't want to re-import my entries but
> the code didn't change much so you should be good to go. Let me know
> if you run into any issues! Let me know if it worked as well and then
> I will close this issue.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/joshstrange/day-one-narrato-import/issues/1#issuecomment-142609727

**Comment by joshstrange** [comment]
If you happened to redownload/clone after my last message you will need to do it again. In adding location support I found a bug that needed fixed for you.

**Comment by jeremycherfas** [comment]
Brilliant! All entries now imported. Minus photos, but that's not
a problem.

I am so grateful to you for making this possible and for helping when I
was stumped.

Best wishes

Jeremy

On Thu, 24 Sep 2015, at 01:17 PM, Josh Strange wrote:

> If you happened to redownload/clone after my last message you will
> need to do it again. In adding location support I found a bug that
> needed fixed for you.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/joshstrange/day-one-narrato-import/issues/1#issuecomment-142912537
